### ISSUE TITLE
Date and Time Not Displaying Correctly When Editing URL Settings

### ISSUE THREAD

**Issue by khanSoliheen** [LyubomirT/url-slicer#10]
<img width="604" alt="Screenshot 2024-09-02 at 20 58 43" src="https://github.com/user-attachments/assets/7c812210-d62d-4b75-8ad9-5b302016760c">

**Comment by khanSoliheen** [comment]
@LyubomirT,  It is fixed. Please assign it to me.

**Comment by LyubomirT** [comment]
> @LyubomirT, It is fixed. Please assign it to me.

Thanks for fixing that, assigning the issue to you.

**Comment by khanSoliheen** [comment]
This PR will fix this https://github.com/LyubomirT/url-slicer/pull/14

**Comment by LyubomirT** [comment]
Issue closed by @khanSoliheen!
