### ISSUE TITLE
Checkbox Selection Sending 'on' Instead of Boolean Value to Backend

### ISSUE THREAD

**Issue by khanSoliheen** [LyubomirT/url-slicer#11]
When a checkbox is selected on the frontend, the form sends the value "on" to the backend. However, the backend expects a boolean value (true or false). This mismatch causes issues with data processing and validation for create and edit process.

**Comment by khanSoliheen** [comment]
@LyubomirT , Please assing it to me. I am gonna raise a PR for it.

**Comment by LyubomirT** [comment]
> @LyubomirT , Please assing it to me. I am gonna raise a PR for it.

I appreciate your continued support, you really are helping the project out quite a lot! Assigning the issue to you, thank you!
