### ISSUE TITLE
📧 Implement email notifications for URL expiration

### ISSUE THREAD

**Issue by LyubomirT** [LyubomirT/url-slicer#5]
Implement an email notification system to alert users about soon-to-expire URLs. Add user preferences to opt-in/out of these notifications.

**Comment by yencolon** [comment]
Hi, can I take this? 🙂

**Comment by LyubomirT** [comment]
> Hi, can I take this? 🙂

Hey there! Sure, you can take the issue, thank you for your interest in contributing to this!
